### ISSUE TITLE
APU is very slow

### ISSUE THREAD

**Issue by iluuu1994** [pcwalton/sprocketnes#30]
Apparently the APU is the bottleneck. Because when you disable it the emulator is blazingly fast (way too fast in fact). I'll see if I can optimize it.

**Comment by iluuu1994** [comment]
The issue is [this piece of code](https://github.com/pcwalton/sprocketnes/blob/master/src/apu.rs#L735-L744). @pcwalton Would you merge this if I found a fix?

**Comment by pcwalton** [comment]
Sure. (It'd be great if there were a maintainer for sprocketnes that wasn't
me; I don't really have time.)

Patrick
